print("Getting to know you!")
print()
yourName = input("You are ")
print(yourName)
foodChoice = input("You're probably hungry for")
print(foodChoice)
favMusic = input("and you're definitely getting your groove on to")
print(favMusic)
print("living in the amazing")
print("Edge of reality")
